### ISSUE TITLE
CSS minification brakes url() param

### ISSUE THREAD

**Issue by ArroWsGM** [litespeedtech/lscache_wp#236]
I'm trying to implement branded background for instagram icon using svg gradient, but plugin brakes CSS rule
```scss
    .social-instagram {
        svg {
            path {
                fill: url(#instagram-icon-gradient)
            }
        }
    }
```
after minification, lscache rewrite url() into `/path-to-theme-css-folder/#instagram-icon-gradient`

We using LiteSpeed Cache v3.2 with WP v5.4.2 and LiteSpeed v7.6
